### ISSUE TITLE
Permissions Rule Class does not update

### ISSUE THREAD

**Issue by thecortex** [dektrium/yii2-rbac#59] opened 2016-03-13 19:39 UTC
Hello,

I tried updating a permission in 
http://local.mydomain.com/backend/rbac/permission/update?name=updateOwnPlace

However, the Rule field, is never updated, and I still get success message after clicking save.
Rule: common\rbac\rules\PlaceOwnerRule

Thanks~

**Comment by shahidt** [comment] 2016-06-14 06:40
I have this same problem too. Could you resolve this?

**Comment by shahidt** [comment] 2016-06-14 07:18
To add more info. I did a server reset and logged out and logged in again. Then I was able to add the rule.

**Comment by thecortex** [comment] 2016-06-14 18:45
I should try it and feed you back

**Comment by dmeroff** [comment] 2016-07-02 14:08
I cannot reproduce this. Could you please provide more information on how to reproduce it (yii2 version, yii2-rbac version, steps to reproduce).

**Comment by thecortex** [comment] 2016-07-03 01:01
Dear Dmitry,

Thank you, but I can't generate the issue again. It seems to be solved. I guess it was related to a problem with my own files that was solved by running 
$ composer install

With kind regards,

**Comment by dmeroff** [comment] 2016-07-03 09:15
Ok, then i'm closing this issue.

**Closed by dmeroff** 2016-07-03 09:15 UTC
Labels: status: to be verified, type: bug
